const POST_STATUS_MODERATED = 'MODERATED';
const POST_STATUSES = ["VALID", "MODERATED"];
const POST_STATUS_VALID = "VALID";



module.exports = {
    POST_STATUSES,
    POST_STATUS_VALID,
    POST_STATUS_MODERATED
};