const PROFILE_STATUS_BLOCKED = 'BLOCKED';
const PROFILE_ROLES = ["ADMIN", "USER", "SYSTEM", 'SUPER_ADMIN'];
const PROFILE_ROLE_SUPER_ADMIN = 'SUPER_ADMIN';
const PROFILE_ROLE_ADMIN = 'ADMIN';
const PROFILE_ROLE_USER = 'USER';
const PROFILE_STATUSES = ["VALID", "BLOCKED"];
const PROFILE_STATUS_VALID = "VALID";



module.exports = {
    PROFILE_STATUS_BLOCKED,
    PROFILE_ROLES,
    PROFILE_ROLE_SUPER_ADMIN,
    PROFILE_ROLE_ADMIN,
    PROFILE_ROLE_USER,
    PROFILE_STATUSES,
    PROFILE_STATUS_VALID
};